# 项目相关配置
ruoyi:
  # 名称
  name: YXX
  # 版本
  version: 3.8.9
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  # 默认为当前项目路径下
  profile: ./yxx/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: '@profiles.active@'
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1024MB
      # 设置总上传的文件大小
      max-request-size: 4096MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  enabled:
    # 数字自动转化字符串
    numToStr: false

## MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.yxx.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

# MyBatis Plus配置
mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: SIMPLE
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    # 如果需要，可以开启驼峰命名法转换字段
#    map-underscore-to-camel-case: true
    # 配置全局枚举处理器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      # 定义属性为deleteFlag的代表为逻辑删除
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  # 搜索指定包别名
  typeAliasesPackage: com.yxx.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 默认开启swagger，是否正式环境关闭swagger
  locked: true
  # 请求前缀
  pathMapping: '/${spring.profiles.active}-api'

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
generator:
  # 激活的代码生成模板
  vmType: yxx
  # 是否开启代码生成基类属性(开启后可以提高生成的代码对MP的兼容性)
  entity: false
