insert into `yxx_dev`.`gen_table` (`table_id`, `table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `tpl_web_type`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (30, 'ai_chat_conversation', '会话表', NULL, NULL, 'AiChatConversation', 'crud', 'element-plus', 'com.yxx.ai', 'ai', 'chatConversation', '会话', 'yxx', '0', '/', '{\"parentMenuId\":3000}', 1, 'admin', '2026-01-21 15:11:01', 1, 'admin', '2026-01-21 15:12:03', '');


insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3010, 30, 'chat_conversation_id', '会话id', 'bigint', 'Long', 'chatConversationId', '1', '1', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 1, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3011, 30, 'chat_group', '会话分组', 'varchar(100)', 'String', 'chatGroup', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 2, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3012, 30, 'chat_title', '会话标题', 'varchar(200)', 'String', 'chatTitle', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 3, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3013, 30, 'create_by_id', '创建者Id', 'bigint', 'Long', 'createById', '0', '0', '0', '0', NULL, '0', NULL, 'EQ', 'input', '', 4, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3014, 30, 'create_by_name', '创建者', 'varchar(64)', 'String', 'createByName', '0', '0', '0', '0', NULL, '1', '1', 'LIKE', 'input', '', 5, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3015, 30, 'create_time', '创建时间', 'datetime', 'LocalDateTime', 'createTime', '0', '0', '1', '0', NULL, '1', '1', 'BETWEEN', 'datetime', '', 6, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3016, 30, 'update_by_id', '更新者Id', 'bigint', 'Long', 'updateById', '0', '0', '0', '0', '0', '0', NULL, 'EQ', 'input', '', 7, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3017, 30, 'update_by_name', '更新者', 'varchar(64)', 'String', 'updateByName', '0', '0', '0', '0', '0', '1', '1', 'LIKE', 'input', '', 8, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3018, 30, 'update_time', '更新时间', 'datetime', 'LocalDateTime', 'updateTime', '0', '0', '1', '0', '0', NULL, NULL, 'BETWEEN', 'datetime', '', 9, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3019, 30, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', '0', '1', '1', '1', '1', 'LIKE', 'textarea', '', 10, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');


insert into `yxx_dev`.`gen_table` (`table_id`, `table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `tpl_web_type`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (31, 'ai_chat_detail', '会话详细表', NULL, NULL, 'AiChatDetail', 'crud', 'element-plus', 'com.yxx.ai', 'ai', 'chatDetail', '会话详细', 'yxx', '0', '/', '{\"parentMenuId\":3000}', 1, 'admin', '2026-01-21 15:11:01', 1, 'admin', '2026-01-21 15:11:48', '');

insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3030, 31, 'chat_detail_id', '会话详细id', 'bigint', 'Long', 'chatDetailId', '1', '1', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 1, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3031, 31, 'chat_conversation_id', '会话id', 'bigint', 'Long', 'chatConversationId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 2, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3032, 31, 'message_type', '消息类型（1代表user 2代表assistant 3代表system 4代表tool）', 'tinyint(1)', 'Integer', 'messageType', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'select', 'ai_message_type', 3, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3033, 31, 'content', '内容', 'text', 'String', 'content', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'editor', '', 4, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3034, 31, 'attachment', '附件', 'text', 'String', 'attachment', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'textarea', '', 5, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3035, 31, 'create_by_id', '创建者Id', 'bigint', 'Long', 'createById', '0', '0', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 6, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3036, 31, 'create_by_name', '创建者', 'varchar(64)', 'String', 'createByName', '0', '0', '0', '0', NULL, '1', '1', 'LIKE', 'input', '', 7, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3037, 31, 'create_time', '创建时间', 'datetime', 'LocalDateTime', 'createTime', '0', '0', '1', '0', NULL, '1', '1', 'EQ', 'datetime', '', 8, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3038, 31, 'update_by_id', '更新者Id', 'bigint', 'Long', 'updateById', '0', '0', '0', '0', '0', NULL, NULL, 'EQ', 'input', '', 9, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3039, 31, 'update_by_name', '更新者', 'varchar(64)', 'String', 'updateByName', '0', '0', '0', '0', '0', '1', '1', 'LIKE', 'input', '', 10, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3040, 31, 'update_time', '更新时间', 'datetime', 'LocalDateTime', 'updateTime', '0', '0', '1', '0', '0', NULL, NULL, 'EQ', 'datetime', '', 11, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
insert into `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) values (3041, 31, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'textarea', '', 12, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');


