INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (54, 5, 'chat_history_id', '会话历史id', 'bigint', 'Long', 'chatHistoryId', '1', '1', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 1, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (55, 5, 'chat_group', '会话分组', 'varchar(100)', 'String', 'chatGroup', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 2, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (56, 5, 'chat_title', '会话标题', 'varchar(200)', 'String', 'chatTitle', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 3, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (58, 5, 'create_by_id', '创建者Id', 'bigint', 'Long', 'createById', '0', '0', '0', '0', NULL, '0', NULL, 'EQ', 'input', '', 4, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (59, 5, 'create_by_name', '创建者名称', 'varchar(64)', 'String', 'createByName', '0', '0', '0', '0', NULL, '1', '1', 'LIKE', 'input', '', 5, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (60, 5, 'create_time', '创建时间', 'datetime', 'LocalDateTime', 'createTime', '0', '0', '1', '0', NULL, '1', '1', 'BETWEEN', 'datetime', '', 6, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (61, 5, 'update_by_id', '更新者Id', 'bigint', 'Long', 'updateById', '0', '0', '0', '0', '0', '0', NULL, 'EQ', 'input', '', 7, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (62, 5, 'update_by_name', '更新者名称', 'varchar(64)', 'String', 'updateByName', '0', '0', '0', '0', '0', '1', '1', 'LIKE', 'input', '', 8, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (63, 5, 'update_time', '更新时间', 'datetime', 'LocalDateTime', 'updateTime', '0', '0', '1', '0', '0', NULL, NULL, 'BETWEEN', 'datetime', '', 9, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (64, 5, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', '0', '1', '1', '1', '1', 'LIKE', 'textarea', '', 10, 1, 'admin', '2025-11-12 20:19:29', 1, 'admin', '2025-11-13 10:46:44', '');



INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (66, 6, 'chat_detail_id', '会话详细id', 'bigint', 'Long', 'chatDetailId', '1', '1', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 1, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (67, 6, 'chat_history_id', '会话历史id', 'bigint', 'Long', 'chatHistoryId', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'input', '', 2, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (68, 6, 'message_type', '消息类型（1代表user 2代表assistant 3代表system 4代表tool）', 'char(1)', 'String', 'messageType', '0', '0', '1', '1', '1', '1', '1', 'EQ', 'select', '', 3, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (69, 6, 'content', '内容', 'text', 'String', 'content', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'editor', '', 4, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (70, 6, 'attachment', '附件', 'text', 'String', 'attachment', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'textarea', '', 5, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (71, 6, 'create_by_id', '创建者Id', 'bigint', 'Long', 'createById', '0', '0', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 6, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (72, 6, 'create_by_name', '创建者名称', 'varchar(64)', 'String', 'createByName', '0', '0', '0', '0', NULL, '1', '1', 'LIKE', 'input', '', 7, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (73, 6, 'create_time', '创建时间', 'datetime', 'LocalDateTime', 'createTime', '0', '0', '1', '0', NULL, '1', '1', 'EQ', 'datetime', '', 8, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (74, 6, 'update_by_id', '更新者Id', 'bigint', 'Long', 'updateById', '0', '0', '0', '0', '0', NULL, NULL, 'EQ', 'input', '', 9, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (75, 6, 'update_by_name', '更新者名称', 'varchar(64)', 'String', 'updateByName', '0', '0', '0', '0', '0', '1', '1', 'LIKE', 'input', '', 10, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (76, 6, 'update_time', '更新时间', 'datetime', 'LocalDateTime', 'updateTime', '0', '0', '1', '0', '0', NULL, NULL, 'EQ', 'datetime', '', 11, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');
INSERT INTO `gen_table_column` (`column_id`, `table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (77, 6, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'textarea', '', 12, 1, 'admin', '2025-11-24 16:32:22', 1, 'admin', '2025-11-24 16:35:22', '');


