-- 单表
INSERT INTO `gen_table` (`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `tpl_web_type`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES ('tb_test_user', '测试单表生成', NULL, NULL, 'TbTestUser', 'crud', 'element-plus', 'com.yxx.business', 'business', 'testUser', '测试单表生成', 'yxx', '0', '/', '{\"parentMenuId\":0}', 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');

-- table_id
SELECT @parentId := LAST_INSERT_ID();

-- table字段
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'user_id', '用户ID', 'bigint', 'Long', 'userId', '1', '1', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 1, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'parent_id', '主表ID', 'bigint', 'Long', 'parentId', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 2, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'user_name', '用户账号', 'varchar(30)', 'String', 'userName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 3, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'password', '密码', 'varchar(100)', 'String', 'password', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 4, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'status', '账号状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'radio', 'sys_normal_disable', 5, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'register_date', '注册日期', 'date', 'Date', 'registerDate', '0', '0', '0', '1', '1', '1', '1', 'BETWEEN', 'date', '', 6, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'register_time', '注册时间', 'datetime', 'DateTime', 'registerTime', '0', '0', '0', '1', '1', '1', '1', 'BETWEEN', 'datetime', '', 7, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_by_id', '创建者Id', 'bigint', 'Long', 'createById', '0', '0', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 8, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_by_name', '创建者名称', 'varchar(64)', 'String', 'createByName', '0', '0', '0', '0', NULL, NULL, NULL, 'LIKE', 'input', '', 9, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'DateTime', 'createTime', '0', '0', '1', '0', NULL, NULL, NULL, 'BETWEEN', 'datetime', '', 10, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_by_id', '更新者Id', 'bigint', 'Long', 'updateById', '0', '0', '0', '0', '0', NULL, NULL, 'EQ', 'input', '', 11, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_by_name', '更新者名称', 'varchar(64)', 'String', 'updateByName', '0', '0', '0', '0', '0', NULL, NULL, 'LIKE', 'input', '', 12, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_time', '更新时间', 'datetime', 'DateTime', 'updateTime', '0', '0', '1', '0', '0', NULL, NULL, 'BETWEEN', 'datetime', '', 13, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', '0', '0', '0', '0', NULL, 'LIKE', 'textarea', '', 14, 1, 'admin', '2025-08-08 18:00:21', 0, '', '2025-08-08 21:58:57', '');



-- 树表
INSERT INTO `gen_table` (`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `tpl_web_type`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES ('tb_test_user_tree', '测试树表', '', '', 'TbTestUserTree', 'tree', 'element-plus', 'com.yxx.business', 'business', 'userTree', '测试树表生成', 'yxx', '0', '/', '{\"treeCode\":\"user_id\",\"treeName\":\"tree_name\",\"treeParentCode\":\"tree_id\",\"parentMenuId\":0}', 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');

-- table_id
SELECT @parentId := LAST_INSERT_ID();

-- table字段
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'user_id', '用户ID', 'bigint', 'Long', 'userId', '1', '1', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 1, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'tree_id', '节点ID', 'bigint', 'Long', 'treeId', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 2, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'tree_name', '节点名称', 'varchar(30)', 'String', 'treeName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 3, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'user_name', '用户账号', 'varchar(30)', 'String', 'userName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 4, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'password', '密码', 'varchar(100)', 'String', 'password', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 5, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'status', '账号状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'radio', 'sys_normal_disable', 6, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'register_date', '注册日期', 'date', 'Date', 'registerDate', '0', '0', '0', '1', '1', '1', '1', 'BETWEEN', 'date', '', 7, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'register_time', '注册时间', 'datetime', 'DateTime', 'registerTime', '0', '0', '0', '1', '1', '1', '1', 'BETWEEN', 'datetime', '', 8, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_by_id', '创建者Id', 'bigint', 'Long', 'createById', '0', '0', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 9, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_by_name', '创建者名称', 'varchar(64)', 'String', 'createByName', '0', '0', '0', '0', NULL, NULL, NULL, 'LIKE', 'input', '', 10, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'DateTime', 'createTime', '0', '0', '1', '0', NULL, NULL, NULL, 'BETWEEN', 'datetime', '', 11, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_by_id', '更新者Id', 'bigint', 'Long', 'updateById', '0', '0', '0', '0', '0', NULL, NULL, 'EQ', 'input', '', 12, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_by_name', '更新者名称', 'varchar(64)', 'String', 'updateByName', '0', '0', '0', '0', '0', NULL, NULL, 'LIKE', 'input', '', 13, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_time', '更新时间', 'datetime', 'DateTime', 'updateTime', '0', '0', '1', '0', '0', NULL, NULL, 'BETWEEN', 'datetime', '', 14, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', '0', '0', '0', '0', NULL, 'LIKE', 'textarea', '', 15, 1, 'admin', '2025-08-08 18:03:53', 0, '', '2025-08-08 18:08:51', '');



-- 主子表
INSERT INTO `gen_table` (`table_name`, `table_comment`, `sub_table_name`, `sub_table_fk_name`, `class_name`, `tpl_category`, `tpl_web_type`, `package_name`, `module_name`, `business_name`, `function_name`, `function_author`, `gen_type`, `gen_path`, `options`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES ('tb_test_user_sub', '测试主表', 'tb_test_user', 'parent_id', 'TbTestUserSub', 'sub', 'element-plus', 'com.yxx.business', 'business', 'userSub', '测试主表生成', 'yxx', '0', '/', '{\"parentMenuId\":0}', 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');

-- table_id
SELECT @parentId := LAST_INSERT_ID();

-- table字段
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'sub_id', '主表ID', 'bigint', 'Long', 'subId', '1', '1', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 1, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'user_name', '用户账号', 'varchar(30)', 'String', 'userName', '0', '0', '1', '1', '1', '1', '1', 'LIKE', 'input', '', 2, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'password', '密码', 'varchar(100)', 'String', 'password', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'input', '', 3, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'status', '账号状态（0正常 1停用）', 'char(1)', 'String', 'status', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'radio', 'sys_normal_disable', 4, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'register_date', '注册日期', 'date', 'Date', 'registerDate', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'date', '', 5, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'register_time', '注册时间', 'datetime', 'DateTime', 'registerTime', '0', '0', '0', '1', '1', '1', '1', 'EQ', 'datetime', '', 6, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_by_id', '创建者Id', 'bigint', 'Long', 'createById', '0', '0', '0', '0', NULL, NULL, NULL, 'EQ', 'input', '', 7, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_by_name', '创建者名称', 'varchar(64)', 'String', 'createByName', '0', '0', '0', '0', NULL, NULL, NULL, 'LIKE', 'input', '', 8, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'create_time', '创建时间', 'datetime', 'DateTime', 'createTime', '0', '0', '1', '0', NULL, NULL, NULL, 'BETWEEN', 'datetime', '', 9, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_by_id', '更新者Id', 'bigint', 'Long', 'updateById', '0', '0', '0', '0', '0', NULL, NULL, 'EQ', 'input', '', 10, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_by_name', '更新者名称', 'varchar(64)', 'String', 'updateByName', '0', '0', '0', '0', '0', NULL, NULL, 'LIKE', 'input', '', 11, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'update_time', '更新时间', 'datetime', 'DateTime', 'updateTime', '0', '0', '1', '0', '0', NULL, NULL, 'BETWEEN', 'datetime', '', 12, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
INSERT INTO `gen_table_column` (`table_id`, `column_name`, `column_comment`, `column_type`, `java_type`, `java_field`, `is_pk`, `is_increment`, `is_required`, `is_insert`, `is_edit`, `is_list`, `is_query`, `query_type`, `html_type`, `dict_type`, `sort`, `create_by_id`, `create_by_name`, `create_time`, `update_by_id`, `update_by_name`, `update_time`, `remark`) VALUES (@parentId, 'remark', '备注', 'varchar(500)', 'String', 'remark', '0', '0', '0', '0', '0', '0', NULL, 'LIKE', 'textarea', '', 13, 1, 'admin', '2025-08-08 18:03:57', 0, '', '2025-08-08 18:09:15', '');
